script:
 - .travis/sass-compile-tester.sh
language: sass
before_install:
 - 'gem install sass'
before_script:
 - 'chmod +x .travis/sass-compile-tester.sh'
 - 'git clone https://github.com/jgthms/bulma.git'
notifications:
 webhooks:
  urls:
   - 'https://www.travisbuddy.com/'
  on_success: never
  on_failure: always
  on_start: never
  on_cancel: never
  on_error: never
